# 약물 데이터 연관성 분석
(https://archive.ics.uci.edu/ml/datasets/Drug+consumption+%28quantified%29)

* 특징
participants were questioned concerning their use of 18 legal and illegal drugs
18가지 legal and illegal drugs 들의 연관성 분석

## 1. 데이터 불러오기 및 전처리

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('drug_consumption.csv',header=None)
cols = ['ID', 'Age','Gender','Edu','Country','Ethnicity','Neuroticism score','Extraversion score',
       'Openness to experience score','Agreeableness score','Conscientiousness score','Impulsiveness score',
        'Sensation seeking score','Alcohol','Amphetamine','Amyl nitrite','Benzodiazepine','Caffeine','Cannabis',
        'Chocolate','Coke','Crack','Ecstacy','Heroin','Ketamine','Legal Highs','LSD','Methadone',
        'Magical Mushroom','Nicotine','Semeron','volatile substance abuse']
data.columns = cols
data

,ID,Age,Gender,Edu,Country,Ethnicity,Neuroticism score,Extraversion score,Openness to experience score,Agreeableness score,...,Ecstacy,Heroin,Ketamine,Legal Highs,LSD,Methadone,Magical Mushroom,Nicotine,Semeron,volatile substance abuse
0,1,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,...,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,2,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,...,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,3,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,...,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,4,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,...,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,5,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,...,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,1884,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,-1.19430,1.74091,1.88511,0.76096,...,CL0,CL0,CL0,CL3,CL3,CL0,CL0,CL0,CL0,CL5
1881,1885,-0.95197,-0.48246,-0.61113,-0.57009,-0.31685,-0.24649,1.74091,0.58331,0.76096,...,CL2,CL0,CL0,CL3,CL5,CL4,CL4,CL5,CL0,CL0
1882,1886,-0.07854,0.48246,0.45468,-0.57009,-0.31685,1.13281,-1.37639,-1.27553,-1.77200,...,CL4,CL0,CL2,CL0,CL2,CL0,CL2,CL6,CL0,CL0
1883,1887,-0.95197,0.48246,-0.61113,-0.57009,-0.31685,0.91093,-1.92173,0.29338,-1.62090,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL4,CL0,CL0
1884,1888,-0.95197,-0.48246,-0.61113,0.21128,-0.31685,-0.46725,2.12700,1.65653,1.11406,...,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL6,CL0,CL2

In [4]:
data1 = data.drop(['ID', 'Age','Gender','Edu','Country','Ethnicity','Neuroticism score',
  'Extraversion score','Openness to experience score','Agreeableness score','Conscientiousness score',
  'Impulsiveness score','Sensation seeking score','Alcohol','Caffeine','Chocolate','Coke','Nicotine'], axis=1)
data1

,Amphetamine,Amyl nitrite,Benzodiazepine,Cannabis,Crack,Ecstacy,Heroin,Ketamine,Legal Highs,LSD,Methadone,Magical Mushroom,Semeron,volatile substance abuse
0,CL2,CL0,CL2,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL0
1,CL2,CL2,CL0,CL4,CL0,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL0,CL0
2,CL0,CL0,CL0,CL3,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0
3,CL0,CL0,CL3,CL2,CL0,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL0,CL0
4,CL1,CL1,CL0,CL3,CL0,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL0,CL0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,CL0,CL0,CL0,CL5,CL0,CL0,CL0,CL0,CL3,CL3,CL0,CL0,CL0,CL5
1881,CL0,CL0,CL0,CL3,CL0,CL2,CL0,CL0,CL3,CL5,CL4,CL4,CL0,CL0
1882,CL6,CL5,CL5,CL6,CL0,CL4,CL0,CL2,CL0,CL2,CL0,CL2,CL0,CL0
1883,CL0,CL0,CL0,CL6,CL0,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL0,CL0
1884,CL3,CL0,CL3,CL3,CL0,CL3,CL0,CL0,CL3,CL3,CL0,CL3,CL0,CL2

**해당 약물(식품)을 사용한 적이 없다. (0)**
- CL0 Never Used

**한번이라도 사용했다. (1)**
- CL1 Used over a Decade Ago
- CL2 Used in Last Decade
- CL3 Used in Last Year
- CL4 Used in Last Month
- CL5 Used in Last Week
- CL6 Used in Last Day

In [5]:
data2=pd.DataFrame(np.where(data1=='CL0', 0, 1))
data2.columns = data1.columns
data2

,Amphetamine,Amyl nitrite,Benzodiazepine,Cannabis,Crack,Ecstacy,Heroin,Ketamine,Legal Highs,LSD,Methadone,Magical Mushroom,Semeron,volatile substance abuse
0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
1,1,1,0,1,0,1,0,1,0,1,1,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,1,0,0
3,0,0,1,1,0,0,0,1,0,0,0,0,0,0
4,1,1,0,1,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,0,0,0,1,0,0,0,0,1,1,0,0,0,1
1881,0,0,0,1,0,1,0,0,1,1,1,1,0,0
1882,1,1,1,1,0,1,0,1,0,1,0,1,0,0
1883,0,0,0,1,0,1,0,0,1,1,0,1,0,0
1884,1,0,1,1,0,1,0,0,1,1,0,1,0,1

## 2. 연관성 분석

In [6]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

### 지지도

In [7]:
frequent_itemsets = apriori(data2, min_support=0.1, use_colnames=True, max_len=3)
frequent_itemsets

C:\Users\jaeyeon\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                                           itemsets
0    0.482228                                      (Amphetamine)
1    0.307692                                     (Amyl nitrite)
2    0.469496                                   (Benzodiazepine)
3    0.780902                                         (Cannabis)
4    0.136870                                            (Crack)
..        ...                                                ...
234  0.116711       (volatile substance abuse, LSD, Legal Highs)
235  0.142175         (Methadone, Magical Mushroom, Legal Highs)
236  0.123607  (volatile substance abuse, Magical Mushroom, L...
237  0.157560                 (Methadone, LSD, Magical Mushroom)
238  0.141645  (volatile substance abuse, LSD, Magical Mushroom)

[239 rows x 2 columns]

### 신뢰도, 향상도

In [8]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.5 )
rules = rules.sort_values("lift", ascending=False)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
289,"(Methadone, Amphetamine)",(Heroin),0.196817,0.148541,0.105040,0.533693,3.592896,0.075804,1.825961,0.898516
292,(Heroin),"(Methadone, Amphetamine)",0.148541,0.196817,0.105040,0.707143,3.592896,0.075804,2.742576,0.847572
541,(Heroin),"(Benzodiazepine, Methadone)",0.148541,0.210610,0.110345,0.742857,3.527168,0.079061,3.069850,0.841481
536,"(Benzodiazepine, Methadone)",(Heroin),0.210610,0.148541,0.110345,0.523929,3.527168,0.079061,1.788514,0.907646
540,(Methadone),"(Benzodiazepine, Heroin)",0.241910,0.140584,0.110345,0.456140,3.244621,0.076336,1.580217,0.912553